### ISSUE TITLE
Crashing with New version of forge.( No ones seeming to answer or fix the problem here)

### ISSUE THREAD

**Issue by ghost** [AlmuraDev/MalisisCore#1]
https://github.com/Ordinastie/MalisisCore/issues/151

**Comment by Dockter** [comment]
I already released a version of MalisisCore on https://ore.spongepowered.org that contains this update.

**Comment by ghost** [comment]
O cause the one I tried on sponge did not work cause I am not using 2705 forge as that is now outdated

**Comment by Dockter** [comment]
Odd, I dont see a gist with that crash log attached.

**Comment by ghost** [comment]
I did not get a crash log, all I had was this

https://github.com/SpongePowered/SpongeForge/issues/2480

**Comment by Dockter** [comment]
Why are you using Forge 2770??  SpongeForge is specifically for 2705.

**Comment by ghost** [comment]
cause there was the new version of forge out that most mod devs updated and Sponge devs just told me the version of spongeforge out works on the new recommended version of forge.

**Comment by Dockter** [comment]
MalisisCore has not been updated past Forge 2705 because SpongeForge has not bumped recommended versions.

**Comment by TacticalUniverse** [comment]
+ my modpack was a WIP till we hit the final stages and now that mod devs moved to the recommended version of forge that's why we had so my pack worked with bugs fixes etc from mod devs but if you ant going to fix it then don't worry about as this will just set my server back

**Comment by Dockter** [comment]
Give me the entire startup log.  Don't blind paste it here.

**Comment by ghost** [comment]
https://gist.github.com/TacticalUniverse/ba349527c6f180042834767f5b3f9e92

**Comment by Dockter** [comment]
Ok, its loading mixin 0.7.11 which is correct.  The error doesn't have anything to do with MalisisCore I believe.

https://gist.github.com/TacticalUniverse/ba349527c6f180042834767f5b3f9e92#file-gistfile1-txt-L65

**Comment by ghost** [comment]
ok well then I am out of luck with my pack till its figured out what's causing it

**Comment by phit** [comment]
I already told you it's VanillaFix in the issue you opened on the Sponge tracker..

**Comment by Dockter** [comment]
This is the main issue:
https://gist.github.com/TacticalUniverse/ba349527c6f180042834767f5b3f9e92#file-gistfile1-txt-L192

MalisisCore doesn't touch Entity at all so MalisisCore isn't the issue.

**Comment by ghost** [comment]
well I link it to them if u can help them fix it
